version: '3'

services:
  db:
    restart: always
    container_name: db
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    build:
      context: ./containers/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    expose:
      - "3306"
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_DB_PATH}:/var/lib/mysql
    depends_on:
      - nginx

  phpmyadmin:
    restart: always
    container_name: phpmyadmin
    build:
      context: ./containers/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - db

  nginx:
    restart: always
    container_name: nginx
    working_dir: /var/www/
    build:
      context: ./containers/nginx
      args:
        - APP_HOST=${APP_HOST}
    volumes:
      - ${APP_SRC}:/var/www/
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - ${NGINX_PORT_80}:80
    depends_on:
      - php-fpm

  php-fpm:
    user: ${CURRENT_UID}
    container_name: php-fpm
    working_dir: /var/www/
    expose:
      - 9000
    build:
      context: ./containers/php-fpm
      args:
        - ENABLE_XDEBUG=${ENABLE_XDEBUG}
    volumes:
      - ${APP_SRC}:/var/www/

  redis:
#    user: ${CURRENT_UID}
    restart: always
    container_name: redis
    build:
      context: ./containers/redis
    expose:
      - 6379
  mailhog:
    user: ${CURRENT_UID}
    restart: unless-stopped
    container_name: mailhog
    build:
      context: ./containers/mailhog
    expose:
      - "1025"
    ports:
      - ${MAILHOG_PORT}:8025
  echo-server:
    restart: always
    container_name: echo-server
    build:
      context: ./containers/echo-server
    ports:
      - 6001
    volumes:
      - ./containers/echo-server/laravel-echo-server.json:/opt/laravellaravel-echo-server.json:ro
    depends_on:
      - redis
  composer:
    user: ${CURRENT_UID}
    working_dir: /var/www/
    container_name: composer
    build:
      context: ./containers/composer
    volumes:
      - ${APP_SRC}:/var/www
  node:
    user: ${CURRENT_UID}
    working_dir: /var/www/
    container_name: node
    build:
      context: ./containers/node
    volumes:
      - ${APP_SRC}:/var/www

