#!/bin/bash
source .env

# Laravel .env file
TARGET_ENV="${APP_SRC}/.env"

# Read options from main .env file and write
# them into Laravel .env file
ENV_FILE=$(<$TARGET_ENV)

ENV_FILE=$(sed "s/APP_NAME=.*/APP_NAME=\"${APP_NAME}\"/" <<< "${ENV_FILE}")
ENV_FILE=$(sed "s/DB_DATABASE=.*/DB_DATABASE=\"${MYSQL_DATABASE}\"/" <<< "${ENV_FILE}")
ENV_FILE=$(sed "s/DB_USERNAME=.*/DB_USERNAME=\"${MYSQL_USER}\"/" <<< "${ENV_FILE}")
ENV_FILE=$(sed "s/DB_PASSWORD=.*/DB_PASSWORD=\"${MYSQL_PASSWORD}\"/" <<< "${ENV_FILE}")
ENV_FILE=$(sed "s/DB_HOST=.*/DB_HOST=database/" <<< "${ENV_FILE}")
ENV_FILE=$(sed "s/MAIL_FROM_ADDRESS=.*/MAIL_FROM_ADDRESS=\"mail@${APP_HOST}\"/" <<< "${ENV_FILE}")
ENV_FILE=$(sed "s/MAIL_FROM_NAME=.*/MAIL_FROM_NAME=\"${APP_NAME}\"/" <<< "${ENV_FILE}")
ENV_FILE=$(sed "s/BROADCAST_DRIVER=.*/BROADCAST_DRIVER=redis/" <<< "${ENV_FILE}")
ENV_FILE=$(sed "s/REDIS_HOST=.*/REDIS_HOST=redis/" <<< "${ENV_FILE}")
ENV_FILE=$(sed "s/MAIL_HOST=.*/MAIL_HOST=mailhog/" <<< "${ENV_FILE}")
ENV_FILE=$(sed "s/MAIL_PORT=.*/MAIL_PORT=1025/" <<< "${ENV_FILE}")
ENV_FILE=$(sed "s/APP_URL=.*/APP_URL=\"http:\/\/${APP_HOST}\"/" <<< "${ENV_FILE}")
echo "${ENV_FILE}" > ${TARGET_ENV}

.docker/scripts/artisan config:clear
.docker/scripts/artisan config:cache
