#!/bin/bash
source ${LARADHOC_BASE_PATH}/.env
mkdir -p ${LARADHOC_BASE_PATH}/$APP_SRC
docker-compose --project-directory ${LARADHOC_BASE_PATH} --project-name "$CONTAINER_PREFIX" run composer create-project --prefer-dist laravel/laravel .
${LARADHOC_BASE_PATH}/.docker/scripts/init-laravel --new
