#!/bin/bash

source ${LARADHOC_BASE_PATH}/.docker/scripts/common/colors

echo -e "\n${ERROR}!!!!!!!!! WARNING !!!!!!!!!${NC}\n"
echo "- all volumes will be REMOVED (you'll loose your MySql data)"
echo "- the ${APP_SRC} folder will be DELETED"
echo "- all containers will be stopped "
echo -e "\nAre your really sure? To confirm, type:   nah\n"

read input
if [ ! "$input" == "nah" ] ; then
  echo -e "\nNobody got hurt :)\n"
  exit 0
fi

source ${LARADHOC_BASE_PATH}/.env
echo "Stopping all containers and removing volumes..."
docker-compose --project-directory ${LARADHOC_BASE_PATH} down -v

echo "Deleting ${APP_SRC} folder..."
rm -rf ${LARADHOC_BASE_PATH}/${APP_SRC}
